const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const STORAGE='nougatstudio.project.v1';
let project={name:'Untitled Project',scenes:[{title:'Opening Scene',location:'Location',characters:'Character',notes:'',html:'<p class="scene">INT. LOCATION - DAY</p><p class="action">Begin writing...</p>'}],activeScene:0,characters:[{name:'Character Name',role:'Role',age:'Current day',voice:'Describe voice and delivery',traits:'Describe personality, habits, strengths, flaws, and defining traits.',backstory:'',reactions:'',continuity:''}],activeCharacter:0,tracked:[]};
function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE));if(v&&v.scenes)project={...project,...v}}catch(e){}renderAll()}
function save(){localStorage.setItem(STORAGE,JSON.stringify(project));$('#saveState').textContent='Saved locally'}
function markDirty(){ $('#saveState').textContent='Saving…';clearTimeout(window._saveTimer);window._saveTimer=setTimeout(save,350)}
function escapeRegex(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function scriptPlainText(){return project.scenes.map(s=>{const d=document.createElement('div');d.innerHTML=s.html;d.querySelectorAll('.term-hit').forEach(x=>x.replaceWith(document.createTextNode(x.textContent)));return d.innerText}).join('\n')}
function countWords(text){const m=text.trim().match(/\b[\w’'-]+\b/g);return m?m.length:0}
function countTerm(term,text=scriptPlainText()){if(!term)return 0;const m=text.match(new RegExp(escapeRegex(term),'gi'));return m?m.length:0}
function renderAll(){ $('#projectName').textContent=project.name;renderScenes();renderCurrentScene();renderCharacters();renderTracked();updateCounts() }
function renderScenes(){const box=$('#sceneList');box.innerHTML='';project.scenes.forEach((s,i)=>{const b=document.createElement('button');b.textContent=`${i+1}. ${s.title||'Untitled Scene'}`;if(i===project.activeScene)b.classList.add('active');b.onclick=()=>{captureScene();project.activeScene=i;renderScenes();renderCurrentScene();save()};box.appendChild(b)});$('#sceneCounter').textContent=`Scene ${project.activeScene+1} of ${project.scenes.length}`}
function renderCurrentScene(){const s=project.scenes[project.activeScene];$('#scriptEditor').innerHTML=s.html;$('#sceneTitleInput').value=s.title||'';$('#sceneLocationInput').value=s.location||'';$('#sceneCharactersInput').value=s.characters||'';$('#sceneNotesInput').value=s.notes||'';highlightEditor();updateCounts()}
function captureScene(){const s=project.scenes[project.activeScene];if(!s)return;s.html=stripHighlights($('#scriptEditor').innerHTML);s.title=$('#sceneTitleInput').value;s.location=$('#sceneLocationInput').value;s.characters=$('#sceneCharactersInput').value;s.notes=$('#sceneNotesInput').value}
function stripHighlights(html){const d=document.createElement('div');d.innerHTML=html;d.querySelectorAll('.term-hit').forEach(x=>x.replaceWith(document.createTextNode(x.textContent)));return d.innerHTML}
function highlightEditor(){const editor=$('#scriptEditor');editor.innerHTML=stripHighlights(editor.innerHTML);if(!project.tracked.length)return;const walker=document.createTreeWalker(editor,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const text=node.nodeValue;let hits=[];project.tracked.forEach(t=>{const r=new RegExp(escapeRegex(t.term),'gi');let m;while((m=r.exec(text)))hits.push({a:m.index,b:m.index+m[0].length,color:t.color})});hits.sort((x,y)=>x.a-y.a);if(!hits.length)continue;const frag=document.createDocumentFragment();let p=0;for(const h of hits){if(h.a<p)continue;frag.append(text.slice(p,h.a));const span=document.createElement('span');span.className='term-hit';span.style.background=h.color;span.textContent=text.slice(h.a,h.b);frag.append(span);p=h.b}frag.append(text.slice(p));node.replaceWith(frag)}}
function renderTracked(){const box=$('#trackedWords');box.innerHTML='';let total=0;project.tracked.forEach((t,i)=>{const n=countTerm(t.term);total+=n;const el=document.createElement('div');el.className='tracked-word';el.innerHTML=`<div class="tracked-word-row"><span class="tracked-word-name"><span class="color-dot" style="background:${t.color}"></span><strong>${t.term}</strong></span><span><span class="count-badge">${n}</span> <button class="mini-button" data-remove="${i}">×</button></span></div>`;el.onclick=e=>{if(e.target.dataset.remove!==undefined)return;showLanguageDetails(t.term)};box.appendChild(el)});$$('[data-remove]').forEach(b=>b.onclick=e=>{e.stopPropagation();project.tracked.splice(Number(b.dataset.remove),1);captureScene();renderTracked();highlightEditor();save()});$('#trackedTotal').textContent=total}
function showLanguageDetails(term){const rows=project.scenes.map((s,i)=>{const d=document.createElement('div');d.innerHTML=s.html;return `${i+1}. ${s.title}: ${countTerm(term,d.innerText)}`}).join('<br>');$('#languageDetails').innerHTML=`<strong>${term}</strong><br>${rows}`}
function updateCounts(){captureScene();const all=scriptPlainText();$('#scriptWordTotal').textContent=countWords(all);const d=document.createElement('div');d.innerHTML=project.scenes[project.activeScene].html;$('#wordCount').textContent=`${countWords(d.innerText)} words`;renderTracked()}
function renderCharacters(){const list=$('#characterList');list.innerHTML='';project.characters.forEach((c,i)=>{const b=document.createElement('button');b.textContent=c.name||'Unnamed Character';if(i===project.activeCharacter)b.classList.add('active');b.onclick=()=>{captureCharacter();project.activeCharacter=i;renderCharacters();loadCharacterForm();save()};list.appendChild(b)});loadCharacterForm()}
function loadCharacterForm(){const c=project.characters[project.activeCharacter];if(!c)return;$('#characterName').value=c.name||'';$('#characterRole').value=c.role||'';$('#characterAge').value=c.age||'';$('#characterVoice').value=c.voice||'';$('#characterTraits').value=c.traits||'';$('#characterBackstory').value=c.backstory||'';$('#characterReactions').value=c.reactions||'';$('#characterContinuity').value=c.continuity||'';$('#characterInitial').textContent=(c.name||'C').trim().charAt(0).toUpperCase()||'C'}
function captureCharacter(){const c=project.characters[project.activeCharacter];if(!c)return;c.name=$('#characterName').value;c.role=$('#characterRole').value;c.age=$('#characterAge').value;c.voice=$('#characterVoice').value;c.traits=$('#characterTraits').value;c.backstory=$('#characterBackstory').value;c.reactions=$('#characterReactions').value;c.continuity=$('#characterContinuity').value}
$('#scriptEditor').addEventListener('input',()=>{captureScene();updateCounts();markDirty()});
['sceneTitleInput','sceneLocationInput','sceneCharactersInput','sceneNotesInput'].forEach(id=>$('#'+id).addEventListener('input',()=>{captureScene();renderScenes();markDirty()}));
['characterName','characterRole','characterAge','characterVoice','characterTraits','characterBackstory','characterReactions','characterContinuity'].forEach(id=>$('#'+id).addEventListener('input',()=>{captureCharacter();renderCharacters();markDirty()}));
$('#trackWordBtn').onclick=()=>{const term=$('#trackedWordInput').value.trim();if(!term)return;if(!project.tracked.some(t=>t.term.toLowerCase()===term.toLowerCase()))project.tracked.push({term,color:$('#trackedWordColor').value});$('#trackedWordInput').value='';captureScene();renderTracked();highlightEditor();save()};
$('#trackedWordInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#trackWordBtn').click()});
$('#newSceneBtn').onclick=()=>{captureScene();project.scenes.push({title:'New Scene',location:'',characters:'',notes:'',html:'<p class="scene">INT. LOCATION - DAY</p><p class="action"><br></p>'});project.activeScene=project.scenes.length-1;renderAll();save()};
$('#addCharacterBtn').onclick=()=>{captureCharacter();project.characters.push({name:'New Character',role:'',age:'',voice:'',traits:'',backstory:'',reactions:'',continuity:''});project.activeCharacter=project.characters.length-1;renderCharacters();save()};
$$('.format-button').forEach(b=>b.onclick=()=>{const sel=window.getSelection();if(!sel.rangeCount)return;let n=sel.anchorNode.nodeType===3?sel.anchorNode.parentElement:sel.anchorNode;while(n&&n.parentElement!==$('#scriptEditor'))n=n.parentElement;if(n&&n!==$('#scriptEditor'))n.className=b.dataset.format;captureScene();markDirty()});
$$('.nav-item').forEach(b=>b.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.workspace').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.workspace+'Workspace').classList.add('active')});
$('#exportBtn').onclick=()=>{captureScene();captureCharacter();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}));a.download='nougatstudio-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$('#importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!data.scenes)throw new Error();project=data;renderAll();save()}catch{alert('That file is not a valid Nougat Studio project.')}};r.readAsText(f)};
load();