const $=s=>document.querySelector(s);const STORAGE='nougatstudio.characters.v1';
let state={active:0,characters:[{name:'Character Name',role:'Role / function in story',age:'',voice:'',occupation:'',origin:'',appearance:'',traits:'',backstory:'',reactions:'',relationships:'',continuity:'',takes:[]}]};
let recorder=null,chunks=[];
function save(){capture();localStorage.setItem(STORAGE,JSON.stringify(state));$('#saveState').textContent='Saved locally'}
function dirty(){ $('#saveState').textContent='Saving…';clearTimeout(window._t);window._t=setTimeout(save,300)}
function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE));if(v&&Array.isArray(v.characters)&&v.characters.length)state=v}catch{}render()}
function c(){return state.characters[state.active]}
function capture(){const x=c();if(!x)return;['name','role','age','voice','occupation','origin','appearance','traits','backstory','reactions','relationships','continuity'].forEach(id=>x[id]=$('#'+id).value)}
function render(){renderList();loadForm();renderTakes()}
function renderList(){const box=$('#characterList');box.innerHTML='';state.characters.forEach((x,i)=>{const b=document.createElement('button');b.className='entry'+(i===state.active?' active':'');b.textContent=x.name||'Unnamed Character';b.onclick=()=>{capture();state.active=i;render();save()};box.appendChild(b)})}
function loadForm(){const x=c();['name','role','age','voice','occupation','origin','appearance','traits','backstory','reactions','relationships','continuity'].forEach(id=>$('#'+id).value=x[id]||'');$('#characterInitial').textContent=(x.name||'C').trim().charAt(0).toUpperCase()||'C'}
function renderTakes(){const box=$('#takes');box.innerHTML='';const x=c();(x.takes||[]).forEach((t,i)=>{const row=document.createElement('div');row.className='take';const audio=document.createElement('audio');audio.controls=true;audio.src=t.data;const del=document.createElement('button');del.className='btn';del.textContent='Delete';del.onclick=()=>{x.takes.splice(i,1);renderTakes();save()};row.append(audio,del);box.appendChild(row)})}
['name','role','age','voice','occupation','origin','appearance','traits','backstory','reactions','relationships','continuity'].forEach(id=>$('#'+id).addEventListener('input',()=>{capture();if(id==='name'){$('#characterInitial').textContent=(c().name||'C').trim().charAt(0).toUpperCase()||'C';renderList()}dirty()}));
$('#addCharacterBtn').onclick=()=>{capture();state.characters.push({name:'New Character',role:'',age:'',voice:'',occupation:'',origin:'',appearance:'',traits:'',backstory:'',reactions:'',relationships:'',continuity:'',takes:[]});state.active=state.characters.length-1;render();save()};
$('#deleteCharacterBtn').onclick=()=>{if(state.characters.length===1){alert('A project needs at least one character record.');return}state.characters.splice(state.active,1);state.active=Math.max(0,state.active-1);render();save()};
$('#exportCharactersBtn').onclick=()=>{capture();const payload=JSON.stringify({format:'Nougat Studio Character Library',version:1,characters:state.characters},null,2);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([payload],{type:'application/json'}));a.download='nougat-studio-characters.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$('#recordBtn').onclick=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});const r=new FileReader();r.onload=()=>{c().takes=c().takes||[];c().takes.push({created:new Date().toISOString(),type:blob.type,data:r.result});renderTakes();save();$('#voiceStatus').textContent='Take saved locally in this browser.'};r.readAsDataURL(blob);stream.getTracks().forEach(t=>t.stop())};recorder.start();$('#recordBtn').classList.add('recording');$('#recordBtn').disabled=true;$('#stopBtn').disabled=false;$('#voiceStatus').textContent='Recording…'}catch(e){$('#voiceStatus').textContent='Microphone access was not available.'}};
$('#stopBtn').onclick=()=>{if(recorder&&recorder.state==='recording')recorder.stop();$('#recordBtn').classList.remove('recording');$('#recordBtn').disabled=false;$('#stopBtn').disabled=true};
load();