const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORAGE='nougatstudio.screenplay.v1';
let project={name:'Untitled Project',activeScene:0,tracked:[],scenes:[{title:'Opening Scene',location:'',characters:'',notes:'',html:'<p class="scene">INT. LOCATION - DAY</p><p class="action">Begin writing...</p>'}]};
function esc(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function escapeRegex(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function stripHighlights(html){const d=document.createElement('div');d.innerHTML=html;d.querySelectorAll('.hit').forEach(x=>x.replaceWith(document.createTextNode(x.textContent)));return d.innerHTML}
function plainFromHtml(html){const d=document.createElement('div');d.innerHTML=html;d.querySelectorAll('.hit').forEach(x=>x.replaceWith(document.createTextNode(x.textContent)));return d.innerText.replace(/\u00a0/g,' ')}
function allText(){capture();return project.scenes.map(s=>plainFromHtml(s.html)).join('\n\n')}
function countWords(t){const m=t.trim().match(/\b[\w’'-]+\b/g);return m?m.length:0}
function countTerm(term,text=allText()){if(!term)return 0;const m=text.match(new RegExp(escapeRegex(term),'gi'));return m?m.length:0}
function save(){localStorage.setItem(STORAGE,JSON.stringify(project));$('#saveState').textContent='Saved locally'}
function dirty(){ $('#saveState').textContent='Saving…';clearTimeout(window.saveTimer);window.saveTimer=setTimeout(save,250)}
function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE));if(v&&Array.isArray(v.scenes)&&v.scenes.length)project={...project,...v}}catch{} renderAll()}
function capture(){const s=project.scenes[project.activeScene];if(!s)return;s.html=stripHighlights($('#scriptEditor').innerHTML);s.title=$('#sceneTitleInput').value;s.location=$('#sceneLocationInput').value;s.characters=$('#sceneCharactersInput').value;s.notes=$('#sceneNotesInput').value}
function renderAll(){renderScenes();renderScene();renderTracked();updateCounts()}
function renderScenes(){const box=$('#sceneList');box.innerHTML='';project.scenes.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.textContent=`${i+1}. ${s.title||'Untitled Scene'}`;if(i===project.activeScene)b.classList.add('active');b.onclick=()=>{capture();project.activeScene=i;renderScenes();renderScene();save()};box.appendChild(b)});$('#sceneCounter').textContent=`Scene ${project.activeScene+1} of ${project.scenes.length}`}
function renderScene(){const s=project.scenes[project.activeScene];$('#scriptEditor').innerHTML=s.html;$('#sceneTitleInput').value=s.title||'';$('#sceneLocationInput').value=s.location||'';$('#sceneCharactersInput').value=s.characters||'';$('#sceneNotesInput').value=s.notes||'';highlight();updateCounts(false)}
function highlight(){const ed=$('#scriptEditor');ed.innerHTML=stripHighlights(ed.innerHTML);if(!project.tracked.length)return;const walker=document.createTreeWalker(ed,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const text=node.nodeValue;let hits=[];for(const t of project.tracked){const r=new RegExp(escapeRegex(t.term),'gi');let m;while((m=r.exec(text)))hits.push({a:m.index,b:m.index+m[0].length,color:t.color})}hits.sort((a,b)=>a.a-b.a);if(!hits.length)continue;const f=document.createDocumentFragment();let p=0;for(const h of hits){if(h.a<p)continue;f.append(text.slice(p,h.a));const span=document.createElement('span');span.className='hit';span.style.background=h.color;span.textContent=text.slice(h.a,h.b);f.append(span);p=h.b}f.append(text.slice(p));node.replaceWith(f)}}
function renderTracked(){const box=$('#trackedWords');box.innerHTML='';let total=0;project.tracked.forEach((t,i)=>{const n=countTerm(t.term);total+=n;const el=document.createElement('div');el.className='tracker-item';el.innerHTML=`<span class="tracker-term"><i class="dot" style="background:${t.color}"></i><strong>${esc(t.term)}</strong></span><span>${n} <button class="mini" data-remove="${i}" type="button">×</button></span>`;box.appendChild(el)});box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{project.tracked.splice(Number(b.dataset.remove),1);capture();renderTracked();highlight();save()});$('#trackedTotal').textContent=total}
function updateCounts(withTracker=true){capture();const sceneText=plainFromHtml(project.scenes[project.activeScene].html);$('#wordCount').textContent=`${countWords(sceneText)} words`;$('#scriptWordTotal').textContent=countWords(project.scenes.map(s=>plainFromHtml(s.html)).join('\n'));if(withTracker)renderTracked()}
function selectedBlock(){const sel=window.getSelection();if(!sel.rangeCount)return null;let n=sel.anchorNode?.nodeType===3?sel.anchorNode.parentElement:sel.anchorNode;while(n&&n.parentElement!==$('#scriptEditor'))n=n.parentElement;return n&&n!==$('#scriptEditor')?n:null}
function download(name,type,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
function fountain(){capture();return project.scenes.map(s=>{const d=document.createElement('div');d.innerHTML=s.html;return [...d.children].map(p=>{const text=p.innerText.trim();if(p.classList.contains('scene'))return text.toUpperCase();if(p.classList.contains('character'))return `\n${text.toUpperCase()}`;if(p.classList.contains('parenthetical'))return text.startsWith('(')?text:`(${text})`;return text}).join('\n')}).join('\n\n')+'\n'}
function htmlExport(){capture();return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(project.name)}</title><style>body{max-width:816px;margin:40px auto;font:12pt/1.45 Courier New,monospace}.scene{text-transform:uppercase;font-weight:bold}.character{text-transform:uppercase;text-align:center;margin-top:22px}.dialogue{width:62%;margin:0 auto 16px}.parenthetical{width:48%;margin:0 auto;text-align:center}</style></head><body>${project.scenes.map(s=>`<section>${stripHighlights(s.html)}</section>`).join('\n')}</body></html>`}
$('#scriptEditor').addEventListener('input',()=>{capture();updateCounts();dirty()});
['sceneTitleInput','sceneLocationInput','sceneCharactersInput','sceneNotesInput'].forEach(id=>$('#'+id).addEventListener('input',()=>{capture();renderScenes();dirty()}));
$$('[data-format]').forEach(b=>b.onclick=()=>{const n=selectedBlock();if(!n)return;n.className=b.dataset.format;capture();dirty()});
$('#newSceneBtn').onclick=()=>{capture();project.scenes.push({title:'New Scene',location:'',characters:'',notes:'',html:'<p class="scene">INT. LOCATION - DAY</p><p class="action"><br></p>'});project.activeScene=project.scenes.length-1;renderAll();save()};
$('#trackWordBtn').onclick=()=>{const term=$('#trackedWordInput').value.trim();if(!term)return;if(!project.tracked.some(t=>t.term.toLowerCase()===term.toLowerCase()))project.tracked.push({term,color:$('#trackedWordColor').value});$('#trackedWordInput').value='';capture();renderTracked();highlight();save()};
$('#trackedWordInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#trackWordBtn').click()});
$('#exportBtn').onclick=()=>{const fmt=$('#exportFormat').value;if(fmt==='fountain')download('screenplay.fountain','text/plain;charset=utf-8',fountain());else if(fmt==='txt')download('screenplay.txt','text/plain;charset=utf-8',allText());else if(fmt==='html')download('screenplay.html','text/html;charset=utf-8',htmlExport());else download('nougat-studio-project.json','application/json',JSON.stringify(project,null,2))};
$('#printBtn').onclick=()=>window.print();
$('#importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{if(f.name.toLowerCase().endsWith('.json')){const data=JSON.parse(r.result);if(!Array.isArray(data.scenes)||!data.scenes.length)throw Error();project={...project,...data};project.activeScene=Math.min(Number(project.activeScene)||0,project.scenes.length-1)}else{const txt=r.result.replace(/\r/g,'');project.scenes=[{title:f.name.replace(/\.[^.]+$/,''),location:'',characters:'',notes:'',html:txt.split('\n').map(line=>`<p class="action">${esc(line)||'<br>'}</p>`).join('')}];project.activeScene=0}renderAll();save()}catch{alert('Nougat Studio could not read that file.')}};r.readAsText(f)};
load();